springdoc:
  swagger-ui:
    path: /swagger-ui-voteBoard.html
    operationsSorter: method
spring:
  profiles:
    include: db
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.springframework.web.servlet: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
