spring:
  profiles:
    include: db
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.springframework.web.servlet: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
